name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:

  check_out:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}

  build_rust:
    runs-on: ubuntu-latest
    needs: check_out
    steps:
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}
          echo "build rust..."

  build_java:
    runs-on: ubuntu-latest
    needs: check_out
    steps:
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}
          echo "build java..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build_rust, build_java]
    steps:
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}
          echo "build java..."
