name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Test
        run: |
          function hello() {
            name="$1"
            text=$(cat <<EOF
            Hello, $name!
            This is a multiline string.
            EOF
            )
            echo "Hello, $text!"
          }
          hello "GitHub Actions"