name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          curl -X POST -H "Content-Type: application/json" \
          post_to_feishu() {
            local text="$1"
            curl -X POST -H "Content-Type: application/json" \
            -d @- https://open.feishu.cn/open-apis/bot/v2/hook/ead5417f-20b9-425c-8ce7-f4b8dd008deb <<EOF
            {
              "msg_type": "text",
              "content": {
                "text": "$text"
              }
            }
            EOF
          }

          PR_INFO=$(cat <<EOF
          PR Title: ${{ github.event.pull_request.title }}
          PR Owner: ${{ github.event.pull_request.user.login }}
          EOF
          
          post_to_feishu "$PR_INFO"
